name: Java CI

on: [push]

## Build maven project: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven#using-the-maven-starter-workflow
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3  ## downloads a copy of your repository on the runner.
      - name: Set up JDK 17
        uses: actions/setup-java@v3 ## configures the Eclipse Temurin (Java) 17 JDK by Eclipse Adoptium.
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Build with Maven ## runs the Maven package target in non-interactive mode to ensure that your code builds, tests pass, and a package can be created.
        run: mvn --batch-mode --update-snapshots package
