name: Java CI

on: [push]

## Build maven project: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven#using-the-maven-starter-workflow
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3  ## downloads a copy of your repository on the runner.
      - name: Set up JDK 17
        uses: actions/setup-java@v3 ## configures the Eclipse Temurin (Java) 17 JDK by Eclipse Adoptium.
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Build with Maven ## runs the Maven package target in non-interactive mode to ensure that your code builds, tests pass, and a package can be created.
        run: mvn --batch-mode -DskipTests package

      - name: Test
        run: mvn --batch-mode -Dmaven.test.failure.ignore=true test

      - name: Report ## https://octopus.com/blog/githubactions-running-unit-tests
        uses: dorny/test-reporter@v1
        if: always() ## generate the report even if the Test step above was set to fail in the event of failed tests.
        with:
          name: Maven Tests
          path: target/surefire-reports/*.xml
          reporter: java-junit
          fail-on-error: true


permissions:
  id-token: write # This is required for requesting the JWT
  contents: read  # This is required for actions/checkout
